version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.18.0
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'